# Generated by Django 5.1.4 on 2025-01-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_diaryuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
    ]
