# Generated by Django 5.1.4 on 2025-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True, verbose_name='Слаг'),
        ),
    ]
