# Generated by Django 5.1.4 on 2025-01-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Слаг'),
        ),
    ]
