# Generated by Django 5.1.4 on 2025-01-14 16:45

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Текст записи'),
        ),
    ]
